---
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ requried_packages }}"


- name: Add docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    state: present
    update_cache: yes

- name: Update apt cache and install docker engine
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ docker_engine }}"

#- name: Install docker-compose
#  remote_user: bbking
#  get_url:
#    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
#    dest: /usr/local/bin/docker-compose
#    mode: 'u+x,g+x'
